name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main  # Sur chaque push sur la branche main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: sudo apt-get install doxygen -y

    - name: Install Graphviz
      run: sudo apt-get install graphviz -y

    - name: Create Output Directory
      run: mkdir -p documentation/v1.0/html  # Crée le chemin requis pour OUTPUT_DIRECTORY

    - name: Generate Documentation
      run: doxygen doxyfile.conf

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./documentation/v1.0/html  # Pointage vers le répertoire de sortie
        destination_dir: v1.0  # Déploiement dans un sous-dossier v1.0
