name: CI - Tests Automatises
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout du code
        uses: actions/checkout@v2
      - name: Configurer Python
        uses: actions/setup-python@v4
        with :
          python-version: '3.10'  # Spécifie la version de Python ici

      - name: Installer les dependances
        run: |
          pip install -r requirements.txt
      - name: Lancer les tests
        run: pytest test_agile/test_workflow.py 
 